- .env.example
- .gitignore
- README.md
- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- host.json
- pom.xml
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventToDataStore.java
Update helm for DEV deploy on AKS
> fix: Dev deploy on AKS kelm

- local.settings.json.example
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventToDataStore.java
> Refactoring on fn

- helm/values-dev.yaml
- helm/values-uat.yaml
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventToDataStore.java
> Fix fn db collection cfg

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- pom.xml
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventEnrichment.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/client/PaymentManagerClient.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/entity/BizEvent.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/entity/Psp.java
- src/test/java/it/gov/pagopa/bizeventsdatastore/BizEventEnrichmentTest.java
- changed retry behaviour
- reduce the call to the function
Junit test
> [PAGOPA-18] fix retry: changed behaviour

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- host.json
- pom.xml
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventEnrichment.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventToDataStore.java
> fix: Add try catch

- helm/Chart.lock
- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- local.settings.json.example
- pom.xml
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventEnrichment.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventTimerTrigger.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/entity/BizEvent.java
- src/test/java/it/gov/pagopa/bizeventsdatastore/BizEventTimerTriggerTest.java
- added trigger function
- Trigger the change feed on an Azure Cosmos DB 
- manual and junit test
> [PAGOPA-603] trigger function failed status retry

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- pom.xml
> fix: Uat deploy

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- pom.xml
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventEnrichment.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventTimerTrigger.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventToDataStore.java
- src/test/java/it/gov/pagopa/bizeventsdatastore/BizEventEnrichmentTest.java
- src/test/java/it/gov/pagopa/bizeventsdatastore/BizEventTimerTriggerTest.java
- changed the update mode from single item to items list
- some cases of inconsistency (error 304) during the update
- manual test
> [Fix error on document save]

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- pom.xml
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventTimerTrigger.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/entity/BizEvent.java
- src/test/java/it/gov/pagopa/bizeventsdatastore/BizEventTimerTriggerTest.java
- added custom error message
- added insert timestamp to BizEvent
- have a dynamic field (chose error field) to force possible updates
- timestamp field as PDND request
manual and junit test
> [PAGOPA-665]: Event timer trigger custom error message and timestamp

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- pom.xml
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventToDataStore.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/entity/BizEvent.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/exception/AppException.java
- src/test/java/it/gov/pagopa/bizeventsdatastore/BizEventToDataStoreTest.java
- Added properties info to biz event
- figure out who uploaded the event to eventhub (serviceIdentifier field)
- Manual and junit test
> [PAGOPA-702] metadata: added properties field to BizEvent

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- pom.xml
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventEnrichment.java
- src/test/java/it/gov/pagopa/bizeventsdatastore/BizEventEnrichmentTest.java
> fix: Add log

- src/test/java/it/gov/pagopa/bizeventsdatastore/BizEventEnrichmentTest.java
- fix junit test
- added missing parameter
> fix_test: fix enrichment test (add id param)

- helm/values-prod.yaml
> fix: Recovery biz

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- pom.xml
> fix : TRIGGER_SQL_QUERY

- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
> fix: Cron time

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- pom.xml
- src/main/java/it/gov/pagopa/bizeventsdatastore/entity/Transfer.java
> fix: Add json alias

- .devops/code-review-pipelines.yml
- .github/workflows/code_review.yml
- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- pom.xml
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventEnrichment.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/client/PaymentManagerClient.java
- src/test/java/it/gov/pagopa/bizeventsdatastore/BizEventEnrichmentTest.java
- src/test/java/it/gov/pagopa/bizeventsdatastore/client/PaymentManagerClientTest.java
- Updates on PM client call with payment method as query parameter
- JUnit tests
> feat: bpay ppal enrich management [PAGOPA-910]

- .devops/deploy-pipelines.yml
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventToDataStore.java
> fix: Add logs BizEventToDataStore for eventId

- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventEnrichment.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/entity/Transaction.java
- src/test/java/it/gov/pagopa/bizeventsdatastore/BizEventEnrichmentTest.java
- src/test/resources/payment-manager/bizEventPM.json
- src/test/resources/payment-manager/bizEventWithTransactionDetails.json
Adding field transactionId that will be copied from idTransaction for the time being. This is done because of the misalignment between PM and NDP. 
This change was required in order to provide NDP the field transactionId they need, until the PM is dismissed. 
This has been tested manually, triggering the function using the cosmos DB dev instance
> feat: adding transactionId field to transaction PAGOPA-1193

- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- pom.xml
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventToDataStore.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/client/RedisClient.java
- src/test/java/it/gov/pagopa/bizeventsdatastore/BizEventToDataStoreTest.java
- src/test/java/it/gov/pagopa/bizeventsdatastore/client/RedisClientTest.java
- added call to redis cache
- Duplicate bizEvents issue mitigation
- Junit and Manual test
> feat: [PAGOPA-1085] duplicated bizevent

- .github/workflows/deploy_with_github_runner.yml
- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
> fix: Upd chart 2.x

- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventToDataStore.java
- added prefix to redis id
- improve checks on redis
- manual test
> feat: [PAGOPA-1230] add prefix

- Dockerfile
- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- host.json
- local.settings.json.example
- pom.xml
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventEnrichment.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventTimerTrigger.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventToDataStore.java
- upgrade extension bundle to [4.0.0, 5.0.0) version
- the version used had reached its EOL:  [see](https://learn.microsoft.com/en-us/azure/azure-functions/migrate-version-3-version-4?tabs=net6-isolated%2Cazure-cli%2Cwindows&pivots=programming-language-java)
-  junit and manual test
> feat: [PAGOPA-1247] upgrade ext bundle [4.0.0, 5.0.0)

- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventToDataStore.java
- src/test/java/it/gov/pagopa/bizeventsdatastore/BizEventToDataStoreTest.java
- added redis connection error handling
- java.net.SocketException: Broken pipe (Write failed) jedis error
- manual test
> bug: [PAGOPA-1263] broken pipe redis

- host.json
> chore: Disable ai sampling

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- host.json
- pom.xml
> [fix-recovery-error]: upgrade sdk

- helm/values-prod.yaml
> fix: Helm prod

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- integration-test/src/features/biz-events-processor.feature
- pom.xml
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventEnrichment.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/entity/Transaction.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/entity/enumeration/UserType.java
- src/test/java/it/gov/pagopa/bizeventsdatastore/BizEventToDataStoreTest.java
- src/test/resources/payment-manager/bizEventECommerce.json
- modified according to ecommerce needs
- events discarded due to the failure to map some fields
> feat: [PAGOPA-1403] upd ecommerce

- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventEnrichment.java
- Modified mapping `transactionDetails.origin`
Considering that the current content of the field `transactionDetails.origin` is always the string `Payment Manager`, Data Lake team asked to us to fill in the field with the same value of `transactionDetails.transaction.origin`
> fix: TransactionDetails.origin mapping changed

- .env.example
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- integration-test/src/config/.env.dev
- integration-test/src/config/.env.local
- integration-test/src/config/.env.uat
- performance-test/src/dev.environment.json
- performance-test/src/local.environment.json
- performance-test/src/uat.environment.json
> chore: Remove ref evh ns01 for ns03

- .env.example
- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- integration-test/src/config/.env.dev
- integration-test/src/config/.env.local
- integration-test/src/config/.env.uat
- performance-test/src/dev.environment.json
- performance-test/src/local.environment.json
- performance-test/src/uat.environment.json
- pom.xml
- src/main/java/it/gov/pagopa/bizeventsdatastore/entity/Transfer.java
- src/test/java/it/gov/pagopa/bizeventsdatastore/BizEventToDataStoreTest.java
- src/test/resources/payment-manager/bizEventModelType1.json
- added IUR field also in Transfer object
- fix failure to capture IUR in transfer object when modelType=1
- junit test
> bug: [PAGOPA-1667] - IUR field in Transfer 

- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- Remove useless `EVENT_HUB_NAMESPACE` environment variables
- Used in integration test only
> chore: update event-hub-ns

- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventToViewDataStoreTimerTrigger.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/entity/enumeration/StatusType.java
- src/test/java/it/gov/pagopa/bizeventsdatastore/BizEventToViewDataStoreTimerTriggerTest.java
- added function to ingest the data from biz container to the views container
- fill the views for retrieving information from the transaction list
- manual and junit test
> feat: [PagoPA-1720] - biz views ingestion

- helm/values-dev.yaml
- helm/values-uat.yaml
> chore: Enabled trx list view

- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
> chore: Migrazione redis multiAZ

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- pom.xml
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventToViewDataStoreTimerTrigger.java
> chore: Ingestion pre PROD release 

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- host.json
- pom.xml
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventToDataStore.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventToViewDataStoreTimerTrigger.java
- src/test/java/it/gov/pagopa/bizeventsdatastore/BizEventToDataStoreTest.java
- made changes to insert retry logic and improved logs
- mitigate the problem related to the loss of some events on the Biz+Datastore side
- manual and junit test
> [PAGOPA-1845] retry log and tuning: first impl

- .github/workflows/deploy_with_github_runner.yml
> chore: Add self host

- helm/values-prod.yaml
> chore: Fix prod ingestion biz

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- pom.xml
- src/main/java/it/gov/pagopa/bizeventsdatastore/service/impl/BizEventToViewServiceImpl.java
- during validation the tax code is transformed into uppercase
- error during validation when the tax code is in lower case
> big: [PAGOPA-1993] - tax code lowercase

- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- host.json
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventEnrichment.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventTimerTrigger.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventToDataStore.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/entity/enumeration/ServiceIdentifierType.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/entity/view/BizEventsViewGeneral.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/service/impl/BizEventToViewServiceImpl.java
- src/test/java/it/gov/pagopa/bizeventsdatastore/service/impl/BizEventToViewServiceImplTest.java
- flag hidden = `false` is automatically set for payments made through IO.  In all other cases the hidden flag will be set to `true`.
- Do not show at IO interface level those payments that were not made by IO channel
- junit test and manual tests
> feat: [PagoPA-2063] - IO payments

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- pom.xml
> update helm channels with checkout

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- pom.xml
- src/main/java/it/gov/pagopa/bizeventsdatastore/service/impl/BizEventToViewServiceImpl.java
- src/test/java/it/gov/pagopa/bizeventsdatastore/service/impl/BizEventToViewServiceImplTest.java
> fix hidden value for payer

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- pom.xml
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventToDataStore.java
- changed level log
- reduce cost
> feat: [PAGOPA-2225] log opt

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- pom.xml
- src/test/java/it/gov/pagopa/bizeventsdatastore/service/impl/BizEventToViewServiceImplTest.java
- src/test/resources/payment-manager/bizEventModCart1.json
- added test for cartMod1 reporting
- incorrect valorization of hidden field
- junit test
> BUG: [PAGOPA-2311] - CartMod1 LAP

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- pom.xml
- src/main/java/it/gov/pagopa/bizeventsdatastore/service/impl/BizEventToViewServiceImpl.java
- src/test/java/it/gov/pagopa/bizeventsdatastore/service/impl/BizEventToViewServiceImplTest.java
- isPayer calculation only from transactionDetails section
- the payer section in the event was enhanced even in the case of unauthenticated channels
- junit test
> BUG: [PAGOPA-2356] - incorrect 'isPayer' info

- .github/workflows/code_review.yml
- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- host.json
- integration-test/src/config/.env.dev
- integration-test/src/config/.env.local
- integration-test/src/config/.env.uat
- performance-test/src/uat.environment.json
- pom.xml
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventToDataStore.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/util/BlobStorage.java
- src/test/java/it/gov/pagopa/bizeventsdatastore/BizEventToDataStoreTest.java
BizEventsToDatastore:
1. ExponentialBackoffRetry configuration, retry interval:
```
1st Retry: 2m
2nd Retry: 4m
3rd Retry: 8m
4th Retry: 16m
5th Retry: 32m
6th Retry and after: 64m (1h)
```
2. Improve exception handling: throw exception to trigger retry mechanism
3. Upload to dead letter blob storage, when:
```
Last Retry input occurs
Last Retry output occurs
Different size between properties and biz events message error occurs
```
4. Update host.json batch size and prefetch count to avoid processing spikes
5. Add Junit tests
Improve fault tolerance when an exception occurs, such as when calls to cosmos fail due to throttling 429
Reduce the write rate to cosmos: the call is asynchronous, this improves load management to the database (better distributed throughout the day and does not …
> feat: PIDM-177 Improve fault tolerance retry handling and dead letter

- .github/workflows/code_review.yml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventEnrichment.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/BizEventToDataStore.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/entity/BizEvent.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/service/BizEventDeadLetterService.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/service/RedisCacheService.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/service/impl/BizEventDeadLetterServiceImpl.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/service/impl/BizEventToViewServiceImpl.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/service/impl/RedisCacheServiceImpl.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/util/BlobStorage.java
- src/test/java/it/gov/pagopa/bizeventsdatastore/BizEventEnrichmentTest.java
- src/test/java/it/gov/pagopa/bizeventsdatastore/BizEventToDataStoreTest.java
- src/test/java/it/gov/pagopa/bizeventsdatastore/client/RedisClientTest.java
Biz-events datastore PM detach + remove useless state
-Detached Payment Manager and refactored both EventHubBizEventProcessor and BizEventEnrichmentProcessor functions including tests.
[PIDM-328](https://pagopa.atlassian.net/jira/software/c/projects/PIDM/boards/2036?assignee=712020%3Afd45de02-0b6c-4ee1-a392-48473b0d70c9&selectedIssue=PIDM-328)
[PIDM-328](https://pagopa.atlassian.net/jira/software/c/projects/PIDM/boards/2036?assignee=712020%3Afd45de02-0b6c-4ee1-a392-48473b0d70c9&selectedIssue=PIDM-328)
[PIDM-328]: https://pagopa.atlassian.net/browse/PIDM-328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PIDM-328]: https://pagopa.atlassian.net/browse/PIDM-328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1K …
> [PIDM-328] fix: Biz-events datastore PM detach + remove useless state

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- pom.xml
> fix port in helm files

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- pom.xml
- src/main/java/it/gov/pagopa/bizeventsdatastore/client/RedisClient.java
- src/main/java/it/gov/pagopa/bizeventsdatastore/service/impl/RedisCacheServiceImpl.java
- src/test/java/it/gov/pagopa/bizeventsdatastore/client/RedisClientTest.java
- single shared connection
- Sharing a JedisPooled instance between multiple functions
- Manual test
> [fix-redis-error] : redis concurrent call error

- .github/workflows/integration_test.yml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
> chore: Fix-integ-test & remove useless helm secrect value
